spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/